sources:
  - MonaSans.glyphs
  - MonaSans-Italic.glyphs
axisOrder:
  - ital
  - wdth
  - wght
familyName: Mona Sans
instances:
  MonaSans[wdth,wght].ttf:
    - coordinates:
        wdth: 75
        wght: 200
    - coordinates:
        wdth: 75
        wght: 300
    - coordinates:
        wdth: 75
        wght: 400
    - coordinates:
        wdth: 75
        wght: 500
    - coordinates:
        wdth: 75
        wght: 600
    - coordinates:
        wdth: 75
        wght: 700
    - coordinates:
        wdth: 75
        wght: 800
    - coordinates:
        wdth: 75
        wght: 900
    - coordinates:
        wdth: 100
        wght: 200
    - coordinates:
        wdth: 100
        wght: 300
    - coordinates:
        wdth: 100
        wght: 400
    - coordinates:
        wdth: 100
        wght: 500
    - coordinates:
        wdth: 100
        wght: 600
    - coordinates:
        wdth: 100
        wght: 700
    - coordinates:
        wdth: 100
        wght: 800
    - coordinates:
        wdth: 100
        wght: 900
    - coordinates:
        wdth: 125
        wght: 200
    - coordinates:
        wdth: 125
        wght: 300
    - coordinates:
        wdth: 125
        wght: 400
    - coordinates:
        wdth: 125
        wght: 500
    - coordinates:
        wdth: 125
        wght: 600
    - coordinates:
        wdth: 125
        wght: 700
    - coordinates:
        wdth: 125
        wght: 800
    - coordinates:
        wdth: 125
        wght: 900
  MonaSans-Italic[wdth,wght].ttf:
    - coordinates:
        wdth: 75
        wght: 200
    - coordinates:
        wdth: 75
        wght: 300
    - coordinates:
        wdth: 75
        wght: 400
    - coordinates:
        wdth: 75
        wght: 500
    - coordinates:
        wdth: 75
        wght: 600
    - coordinates:
        wdth: 75
        wght: 700
    - coordinates:
        wdth: 75
        wght: 800
    - coordinates:
        wdth: 75
        wght: 900
    - coordinates:
        wdth: 100
        wght: 200
    - coordinates:
        wdth: 100
        wght: 300
    - coordinates:
        wdth: 100
        wght: 400
    - coordinates:
        wdth: 100
        wght: 500
    - coordinates:
        wdth: 100
        wght: 600
    - coordinates:
        wdth: 100
        wght: 700
    - coordinates:
        wdth: 100
        wght: 800
    - coordinates:
        wdth: 100
        wght: 900
    - coordinates:
        wdth: 125
        wght: 200
    - coordinates:
        wdth: 125
        wght: 300
    - coordinates:
        wdth: 125
        wght: 400
    - coordinates:
        wdth: 125
        wght: 500
    - coordinates:
        wdth: 125
        wght: 600
    - coordinates:
        wdth: 125
        wght: 700
    - coordinates:
        wdth: 125
        wght: 800
    - coordinates:
        wdth: 125
        wght: 900
